name: psr_base
description: Projects Sources Requirement For Dornica
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  hive:
  hive_flutter:
  image_picker:
  intl:
  package_info_plus: ^1.4.2
  path:
  path_provider:
  permission_handler:
  plugin_platform_interface:
  responsive_builder:
  shamsi_date:
  shared_preferences:
  sliding_sheet:
  web_socket_channel:
  hive_generator:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:
  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
